[git_branch]
symbol = ""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmd_duration]
disabled = true

[line_break]
disabled = false

[package]
disabled = true

add_newline = false

[battery]
disabled = true
